### ISSUE TITLE
trimModelList problems

### ISSUE THREAD

**Issue by durack1** [durack1/durolib#27]
```
    ...: tasTosTrim = trimModelList(tasTos)
Traceback (most recent call last):

  File "<ipython-input-18-c8ced1d870c0>", line 13, in <module>
    tasTosTrim = trimModelList(tasTos)

  File "durolib/lib/durolib.py", line 1077, in trimModelList
    modelFileListCreationDate = map(cdt.s2c,modelFileListCreationDate)

ValueError: Invalid component time
```

**Comment by durack1** [comment]
Problem file is
```
# Remove problem file
tas.remove('/work/cmip5-test/historical/atm/mo/tas/cmip5.GFDL-CM3.historical.r2i1p1.mo.
atm.Amon.tas.ver-v20120227.latestX.xml')
```

**Comment by durack1** [comment]
There are other issues found with `BCC` data at `/data_crunchy_oceanonly/crunchy_work/cmip-dyn/CMIP6/CMIP/historical/ocean/mon/thetao/*.xml`
